#!/usr/bin/env bash

pacman -Sy --needed --noconfirm git

cd "$HOME" || exit

git clone https://github.com/Tifeko/archTifeko.git

# list all conected disks
lsblk -o name,size,type
# ask for the disk to install arch on
echo "Enter the disk to install arch on (example: sda):"
read -r DISK
echo $DISK


