#!/usr/bin/env bash

pacman -Sy --needed --noconfirm git

cd "$HOME" || exit

git clone https://github.com/Tifeko/archTifeko.git

dialog --title "ArchTifeko" --yesno "Do you have your disks mounted at /mnt?" 0 0 || exit

cd archTifeko/scripts || exit
"$HOME"/archTifeko/scripts/0_preinstall
"$HOME"/archTifeko/scripts/1_installwithoutchroot
cp "$HOME"/archTifeko/scripts/2_installwithchroot /mnt/root/2_installwithchroot
arch-chroot /mnt sh /root/2_installwithchroot
cp "$HOME"/archTifeko/scripts/3_chrootuser /mnt/root/3_chrootuser
NEWUSERNAME=$( cat /mnt/root/archTifeko/options/username )
arch-chroot /mnt runuser -u $NEWUSERNAME -- sh /root/3_chrootuser