#!/usr/bin/bash

NEWHOSTNAME=$( dialog --title "ArchTifeko" --inputbox "Type your new hostname" 0 0 "archlinux" 3>&1 1>&2 2>&3 3>&- ); clear
NEWUSERNAME=$( dialog --title "ArchTifeko" --inputbox "Type your new username" 0 0 3>&1 1>&2 2>&3 3>&- ); clear
NEWPASSWORD=$( dialog --title "ArchTifeko" --insecure --passwordbox "Type your new password" 0 0 3>&1 1>&2 2>&3 3>&- ); clear
NEWTIMEZONE=$( dialog --title "ArchTifeko" --inputbox "Type you timezone" 0 0 "$( curl --fail https://ipapi.co/timezone )" 3>&1 1>&2 2>&3 3>&- ); clear
dialog --title "ArchTifeko" --yesno "Do you want to install yay?" 0 0 && YAY=1 || YAY=0
PROFILE=$( dialog --title "ArchTifeko" --menu "Select your profile" 0 0 0 \
            1 "dwm-Tifeko" \
            2 "Gnome"      \
            3 "KDE Plasma" \
            4 "Minimal"    \
            3>&1 1>&2 2>&3 3>&- ); clear
DRIVE=$( dialog --title "ArchTifeko" --inputbox "which device does the bootloader has to get installed on?" 0 0 3>&1 1>&2 2>&3 3>&- ); clear

mkdir -pv /mnt/root/archTifeko/options
echo "$NEWHOSTNAME" >> /mnt/root/archTifeko/options/hostname
echo "$NEWUSERNAME" >> /mnt/root/archTifeko/options/username
echo "$NEWPASSWORD" >> /mnt/root/archTifeko/options/password
echo "$PROFILE" >> /mnt/root/archTifeko/options/profile
echo "$NEWTIMEZONE" >> /mnt/root/archTifeko/options/timezone
echo "$YAY" >> /mnt/root/archTifeko/options/yay
echo "$DRIVE" >> /mnt/root/archTifeko/options/drive