#!/usr/bin/bash

TIMEZONE=$( cat /root/archTifeko/options/timezone )
NEWHOSTNAME=$( cat /root/archTifeko/options/hostname )
NEWUSERNAME=$( cat /root/archTifeko/options/username )
NEWPASSWORD=$( cat /root/archTifeko/options/password )
DRIVE=$( cat /root/archTifeko/options/drive )

ln -sf "/usr/share/zoneinfo/$TIMEZONE" /etc/localtime
hwclock --systohc
rm /etc/locale.gen
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo "$NEWHOSTNAME" >> /etc/hostname

proc_type=$(lscpu)
if grep -E "GenuineIntel" <<< ${proc_type}; then
    echo "Installing Intel microcode"
    pacman -S --noconfirm --needed intel-ucode
    proc_ucode=intel-ucode.img
elif grep -E "AuthenticAMD" <<< ${proc_type}; then
    echo "Installing AMD microcode"
    pacman -S --noconfirm --needed amd-ucode
    proc_ucode=amd-ucode.img
fi

groupadd libvirt,sudo
useradd -m -G wheel,libvirt -s /bin/bash "$NEWUSERNAME"
echo "$NEWUSERNAME:$NEWPASSWORD" | chpasswd

grubeufiinstall() {
    pacman -S --needed --noconfirm efibootmgr
    grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
}

[ -d /sys/firmware/efi ] && grubeufiinstall || grub-install --target=i386-pc "$DRIVE"
grub-mkconfig -o /boot/grub/grub.cfg

if [ -z "$1" ]; then

  # When you run the script, you will run this block since $1 is empty.

  echo "Starting up visudo with this script as first parameter"

  # We first set this script as the EDITOR and then starts visudo.
  # Visudo will now start and use THIS SCRIPT as its editor
  export EDITOR=$0 && sudo -E visudo
else

  # When visudo starts this script, it will provide the name of the sudoers 
  # file as the first parameter and $1 will be non-empty. Because of that, 
  # visudo will run this block.

  echo "Changing sudoers"

  # We change the sudoers file and then exit  
  echo "%sudo ALL=(ALL) ALL" >> "$1"
fi
